### ISSUE TITLE
Detected rectangles are drawn with an offset from the original detection.

### ISSUE THREAD

**Issue by nonoesp** [ModelDepot/tfjs-yolo-tiny-demo#1] opened 2018-04-15 17:37 UTC
Hi Mike!

I've realized that there is a mismatch between the *detected* position of an object and where its bounding box is drawn.

I'm currently trying to fix this — let me know if there is a known fix for this =).

Thanks!

**Comment by MikeShi42** [comment] 2018-04-15 19:08
Oh no! I wasn't aware of such a bug but I'm glad you caught it! I'm looking forward to the PR or if I can help in any way :)

**Comment by nonoesp** [comment] 2018-04-16 16:09
I'll try to get a pull request in! The problem seems to be that TensorFlow.js is cropping the image but the camera feed video is not properly centered.

**Comment by MikeShi42** [comment] 2018-04-16 19:38
Ah okay that's weird I just had a chance to check the demo again, I have a feeling this is a regression since I didn't face such bad offsets before. My gut says it might have to do with https://github.com/ModelDepot/tfjs-yolo-tiny-demo/commit/d3d0e63298d5f94a12b7c78b5f627b49bbdc8314. I'll look into it a bit as well.

**Comment by MikeShi42** [comment] 2018-04-16 19:47
Ooh found the root issues, it's located here: https://github.com/ModelDepot/tfjs-yolo-tiny-demo/blob/65c4d919871eed54a1429e656615f028c76e6bee/src/index.js#L85

I overwrote the element to display as block instead of flex, therefore not allowing it to center the child webcam element :(

Thanks so much for the catch, I'll have a commit in soon, sorry to steal the issue away from you :(

**Comment by MikeShi42** [comment] 2018-04-16 19:49
Fixed in https://github.com/ModelDepot/tfjs-yolo-tiny-demo/commit/d980f957328cd8acb95f4052e6a21d61804efe90

**Closed by MikeShi42** 2018-04-16 19:49 UTC

**Comment by nonoesp** [comment] 2018-04-16 21:29
Great! Thanks for the fix.
